services:
  db:
    build: ./database/
    ports:
      - "5555:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: forum-db
  backend:
    build: ./backend/
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src/:/backend/src/
  frontend:
    build: ./frontend/
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/code/:/frontend/code/